### ISSUE TITLE
Crash at None value on Solana validator > 1.8.5

### ISSUE THREAD

**Issue by kernelpanic9** [rustiqtech/solana-exporter#45]
Unable to run exporter after upgrade to 1.8.5 and up.
I did try to enable `--enable-rpc-transaction-history` flag on the validator, but that didn't help.

Trace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/gauges.rs:282:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:735:21
   4: solana_exporter::gauges::PrometheusGauges::export_epoch_info::{{closure}}
             at ./src/gauges.rs:271:19
   5: solana_exporter::rpc_extra::with_first_block
             at ./src/rpc_extra.rs:17:9
   6: solana_exporter::gauges::PrometheusGauges::export_epoch_info
             at ./src/gauges.rs:269:9
   7: solana_exporter::main::{{closure}}
             at ./src/main.rs:174:9
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
   9: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/park/thread.rs:263:54
  10: tokio::coop::with_budget::{{closure}}
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:106:9
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  12: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  13: tokio::coop::with_budget
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:99:5
  14: tokio::coop::budget
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:76:5
  15: tokio::park::thread::CachedParkThread::block_on
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/park/thread.rs:263:31
  16: tokio::runtime::enter::Enter::block_on
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/enter.rs:151:13
  17: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/mod.rs:71:9
  18: tokio::runtime::Runtime::block_on
             at /home/sol/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/mod.rs:452:43
  19: solana_exporter::main
             at ./src/main.rs:161:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zikarad** [comment]
Confirmation of previous report (runnig solana-validator 1.8.14):
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/gauges.rs:282:22
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ComaGoob** [comment]
having this same issue on 1.10.26 with very similar logs.  Anyone know the cause of this issue ?
